package com.example.employee.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.Data;

import java.time.LocalDate;
import java.util.List;

@Data
@Entity
public class Employee {

    @Id
    @NotBlank
    private String employeeId;

    @NotBlank
    private String firstName;

    @NotBlank
    private String lastName;

    @Email
    @NotBlank
    private String email;

    @ElementCollection
    @Size(min = 1, message = "At least one phone number is required.")
    private List<@Pattern(regexp = "^\\d{10}$", message = "Phone number must be 10 digits.") String> phoneNumbers;

    @NotNull
    private LocalDate doj;

    @Positive
    private double salary;

    // Additional fields for tax calculations
    @Transient
    private double yearlySalary;

    @Transient
    private double taxAmount;

    @Transient
    private double cessAmount;

    // Constructors, Getters, and Setters will be generated by Lombok (@Data)
}